FROM python:3.12-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dbt-core \
    dbt-sqlserver \
    dagster-dbt
# NY
WORKDIR /opt/dagster/app
COPY /dbt /opt/dagster/app/dbt
# Add code location code
WORKDIR /opt/dagster/app/dagster_dev_project
#COPY /dagster_app/ /opt/dagster/app

#RUN mkdir -p dagster_dev_project
#COPY /dagster_dev_project/pyproject.toml /opt/dagster/app
COPY /dagster_dev_project /opt/dagster/app/dagster_dev_project

RUN pip install -e /opt/dagster/app/dagster_dev_project

# Run dagster code server on port 4000
EXPOSE 4000

HEALTHCHECK --timeout=1s --start-period=3s --interval=3s --retries=20 CMD ["dagster", "api", "grpc-health-check", "-p", "4000"]

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "/opt/dagster/app/dagster_dev_project/src/dagster_dev_project/definitions.py"]